### ISSUE TITLE
Does LinkChecker work with Umbraco v8?

### ISSUE THREAD

**Issue by irongut** [DanDiplo/Diplo.LinkChecker#11]
I'm using Umbraco v8.5.4 and would like to know if Diplo.LinkChecker will work with it? The Umbraco packages site does not list compatibility with any Umbraco v8 version.

**Comment by DanDiplo** [comment]
Hi,

Sorry, no, it was released for v7 only.

**Comment by irongut** [comment]
@DanDiplo Thanks for the quick reply. I'll use an external checker.
