### ISSUE TITLE
Diacritics in URL

### ISSUE THREAD

**Issue by ssougnez** [DanDiplo/Diplo.LinkChecker#5]
Hello,

I'm working on a french site and some URL contain diacritics such "http://www.site.be/été". 
Diplo.LinkChecker marks all the site containing diacritics as invalid as they get encoded as: http://www.site.be/&#233;t&#233;/

**Comment by DanDiplo** [comment]
Hi,

Thanks for pointing this out. I've never tested it on a site with that type of encoding in the URLs, so will look into it.

**Comment by ssougnez** [comment]
I can have a look at it if you want ;-)

**Comment by ssougnez** [comment]
Hi, I had a bit of time this afternoon, so I had a look and created this PR: https://github.com/DanDiplo/Diplo.LinkChecker/pull/6

Cheers

**Comment by DanDiplo** [comment]
Excellent, that's the type of bug report I like - the one with a fix :)

**Comment by DanDiplo** [comment]
I've now released this as a package - https://our.umbraco.com/projects/backoffice-extensions/diplo-link-checker/ - I'll look into NuGet shortly. Thanks for your help and input.
